### PR TITLE
feat(packaging): generate sourcemaps

### LINKED ISSUE #662: build: publish sourcemap in release
## What problem does this feature solve?

Current build process:

```
             ngc                           rollup                        tsc                     rollup                     uglify
ts (source) ----> js (esm2015, separated) -------> js (esm2015, bundle) ----> js (esm5, bundle) -------> js (umd5, bundle) -------> js (umd5, bundle, min)
```

The `tsc` step makes it impossible to generate sourcemap for es5 target (`tsc` cannot consume input sourcemap).

Should be changed to:

```
             ngc                           rollup
ts (source) ----> js (esm2015, separated) -------> js (esm2015, bundle)
           | ngc                        rollup
           |----> js (esm5, separated) -------> js (esm5, bundle)
                                      | rollup
                                      |-------> js (umd5, bundle)
                                      | rollup
                                      |-------> js (umd5, bundle, min)
```

## What does the proposed API look like?

N/A.

### PR DESCRIPTION
**Pull request by trotyl**
Closes #662
BREAKING CHANGE: umd file name simplified from 'ng-zorro-antd.js' to 'antd.js'

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: closes #662

## What is the new behavior?

Change summary:

+ Redesign the build-process as mentioned in #662;
+ Rename publish folder `esm15` -> `esm2015` as per https://github.com/angular/angular/commit/15e8d5031358fe8469fc746157e4aefeb1e3d274;
+ Rename `index.xxx` to `antd.xxx` to avoid potential barrel usage; 
+ Simplify umd file name in `bundles` folder from `ng-zorro-antd.js` to `antd.js`;
+ Enable source-maps.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

The file name of umd bundle changed from `ng-zorro-antd.umd[.min].js` to `antd[.min].js`, the prefix is unnecessary in file name.

### CODE REVIEW

**Comment by trotyl** [comment]
Ready for review.

**Comment by trotyl** [comment]
Ready for review.

**Comment by vthinkxie** [comment]
why not keep the original name `ng-zorro-antd.js`, it may confuse the users with the same name with react version.

**Comment by trotyl** [comment]
Whoever use the umd file must specify the npm package name like:

+ `<script src="https://unpkg.com/ng-zorro-antd@0.6.2/bundles/antd.umd.js">`
+ `require('ng-zorro-antd/bundles/antd.umd.js')`

It will always be a duplication, isn't it?

**Comment by vthinkxie** [comment]
ok, that is fine.

**Pull request merged**
