### PR TITLE
chore: support for running npm scripts in windows

### PR DESCRIPTION
**Pull request by wisenchen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #7982

Resolve local 'npm run start' Out of Memory issue

## What is the new behavior?

The 'npm run start' command now uses more memory to prevent out of memory errors.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wisenchen** [comment]
Hi there, thank you for your suggestion! 
I have already updated the package-lock.json file by running `npm i cross-env --save-dev` as you instructed.

**Review by Laffery — APPROVED** [review]
LGTM

**Comment by Laffery** [comment]
@HyperLife1119 why do you add these commits?
image

**Comment by HyperLife1119** [comment]
> @HyperLife1119 why do you add these commits? image

I didn't do anything, maybe @wisenchen didn't rebase correctly.

**Comment by Laffery** [comment]
> > @HyperLife1119 why do you add these commits? image
> 
> I didn't do anything, maybe @wisenchen didn't rebase correctly.

@wisenchen Could you please rebase again and make this pr only include your commits?

**Comment by wisenchen** [comment]
> > > @HyperLife1119 why do you add these commits? image
> > 
> > 
> > I didn't do anything, maybe @wisenchen didn't rebase correctly.我什么都没做，也许@wisenchen没有正确地变基。
> 
> @wisenchen Could you please rebase again and make this pr only include your commits?
Sure, I apologize for the confusion earlier. I have corrected the issue by rebasing and ensuring that this pull request now only includes my commits.

**Review by Laffery — APPROVED** [review]
LGTM

**Pull request merged**
