### PR TITLE
fix(module:input): support reactive form disabled

### PR DESCRIPTION
**Pull request by nuonuoge**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/5307

**Comment by nuonuoge** [comment]
> any reason to change the code? any related issues?
https://stackblitz.com/edit/angular-aveg5n-m7xjmv?file=src/app/app.component.ts

when use form.get('xxx').disable(); it's not work

**Comment by vthinkxie** [comment]
I think #5307 should be fixed with update the disabled$ inside input directive, the bug is not caused by the attribute of nz-input, but the class of nz-input-group.

**Comment by nuonuoge** [comment]
>https://stackblitz.com/edit/angular-fumfvw?file=src/app/app.component.ts

the @input disabled is not changed, you can see the class does not has 'ant-input-disabled'，only native disabled work
image

image

**Comment by vthinkxie** [comment]
> > https://stackblitz.com/edit/angular-fumfvw?file=src/app/app.component.ts
> 
> the @input disabled is not changed, you can see the class does not has 'ant-input-disabled'，only native disabled work
> image
> 
> image
> image

there are still some fixes needed, I have submitted it here https://github.com/NG-ZORRO/ng-zorro-antd/pull/5428
thanks for your PR anyway

**Pull request merged**
