### PR TITLE
feat(module:collapse): change nzExpandIconPosition type from `left` | `right` to `start` | `end`

### PR DESCRIPTION
**Pull request by HyperLife1119**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

https://4x.ant.design/components/collapse-cn/#:~:text=%2D-,expandIconPosition,-%E8%AE%BE%E7%BD%AE%E5%9B%BE%E6%A0%87

## What is the new behavior?

Parameter types are aligned with antd.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

### CODE REVIEW

**Review by OriginRing — APPROVED** [review]

**Comment by OriginRing** [comment]
LGTM

**Comment by Laffery** [comment]
document should be updated as well :)

**Comment by HyperLife1119** [comment]
> document should be updated as well :)

done

**Review by Laffery — APPROVED** [review]
LGTM

**Pull request merged**
