### PR TITLE
feat: Angular 16 support

### PR DESCRIPTION
**Pull request by youssef3wi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[x] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #7929

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by youssef3wi** [comment]
I apologize, but it appears that using TypeScript results in fewer changes and restrictions.

Like:
- input validation
- schematics deprecations
- and more

**Comment by Nicoss54** [comment]
> I apologize, but it appears that using TypeScript results in fewer changes and restrictions.
> 
> Like:
> 
> * input validation
> * schematics deprecations
> * and more

True :) thats why in the PR #7934 schematics change and some other component file change to integrate typescript 5.0.2

Deprecating method was replaced by the correct one and a new file was created for the getFileContent method. 

This PR is still in draft because the packages
- @angular-builders/custom-webpack 
- Ant-design-icons/angular 

are still in version 15 ;)

In an other PR it could be a great idea to integrate the new required input feature but I think this shouldn't be done in the same PR of the migration of angular 16

**Comment by youssef3wi** [comment]
Yes in progress for `@angular-builders/custom-webpack`

**Comment by Nicoss54** [comment]
duplicate #7934

**Pull request closed without merging**
