### PR TITLE
fix(moment): use replace plugin to replace moment

### PR DESCRIPTION
**Pull request by LinBoLen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #315 #85 #169 #240

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by trotyl** [comment]
We don't provide sourcemap at all, what is it going to fix?

**Comment by LinBoLen** [comment]
error occurs in my project. if there are no correct sourcemap file. rollup can't bundle file

# Before

```
import sourcemaps from 'rollup-plugin-sourcemaps';
import replace from 'rollup-plugin-replace';

function replaceMoment() {
  return {
    name: 'replace-moment-import',
    transform: code =>
            ({
              code: code.replace('import * as moment', 'import moment'),
            })
  }
}
export default {plugins: [replaceMoment(), sourcemaps()]};
```

can't generate bundle file from esm5/index.js
----
image

sourcemap file is incorrectly
----
image



# After
```
import sourcemaps from 'rollup-plugin-sourcemaps';
import replace from 'rollup-plugin-replace';

export default { plugins: [replace({ "import * as moment": "import moment" }),sourcemaps()] };
```

----
image

----

**Comment by trotyl** [comment]
The process for generating esm5 index file is: `ngc` -> `rollup` -> `tsc`, as `tsc` won't consume the input sourcemap generated by `rollup`, the final sourcemap would be wrong anyway.

Actually the input sourcemap feature is not landed yet: `https://github.com/Microsoft/TypeScript/issues/13944`.

What's the benefit for having a wrong soucemap over not having it?

**Comment by trotyl** [comment]
Another question, would `rollup` consume the input sourcemap from `ngc`? The input files for `rollup` are already generated files.

**Comment by trotyl** [comment]
This PR is fine except title not being helpful.

**Pull request merged**
