### PR TITLE
fix(module:i18n): Danish locale is exported and mentioned in i18n docs

### PR DESCRIPTION
**Pull request by michaelkrog**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #2598

## What is the new behavior?
Danish locale is actually exported

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by vthinkxie** [comment]
Hi @michaelkrog 
there has conflicts with master now, would plz rebase it? thanks!

**Comment by michaelkrog** [comment]
Sure. I'll take a look at it now!

**Comment by michaelkrog** [comment]
@vthinkxie There.  It should be alright now...

**Comment by michaelkrog** [comment]
Hmm.  Test fails, but I can't see that it should be anything related to the changes of this PR:
```
Chromium 62.0.3202 (Ubuntu 0.0.0) tabs basic tabs should prevent focus scroll FAILED
	Expected false to be true.
	    at UserContext.<anonymous> (http://localhost:9876/tabs/nz-tabs.spec.ts?:457:49)
	    at UserContext.<anonymous> (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:1424:1)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone.js?:388:1)
	    at ProxyZoneSpec.push.../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:288:1)
Chromium 62.0.3202 (Ubuntu 0.0.0): Executed 1097 of 1291 (1 FAILED) (skipped 2) (0 secs / 3 mins 37.938 secs)
Chromium 62.0.3202 (Ubuntu 0.0.0) tabs basic tabs should prevent focus scroll FAILED
	Expected false to be true.
	    at UserContext.<anonymous> (http://localhost:9876/tabs/nz-tabs.spec.ts?:457:49)
	    at UserContext.<anonymous> (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:1424:1)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone.js?:388:1)
	    at ProxyZoneSpec.push.../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:288:1)
Chromium 62.0.3202 (Ubuntu 0.0.0) tabs init nzTabPosition to left should next and prev buttons display abnormal FAILED
	Expected ant-tabs-nav-container ant-tabs-nav-container-scrolling not to contain 'ant-tabs-nav-container-scrolling'.
	    at UserContext.<anonymous> (http://localhost:9876/tabs/nz-tabs.spec.ts?:470:89)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone.js?:388:1)
	    at ProxyZoneSpec.push.../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:288:1)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone.js?:387:1)
Chromium 62.0.3202 (Ubuntu 0.0.0): Executed 1098 of 1291 (2 FAILED) (skipped 2) (0 secs / 3 mins 38.049 secs)
Chromium 62.0.3202 (Ubuntu 0.0.0) tabs init nzTabPosition to left should next and prev buttons display abnormal FAILED
	Expected ant-tabs-nav-container ant-tabs-nav-container-scrolling not to contain 'ant-tabs-nav-container-scrolling'.
	    at UserContext.<anonymous> (http://localhost:9876/tabs/nz-tabs.spec.ts?:470:89)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone.js?:388:1)
	    at ProxyZoneSpec.push.../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/node_modules/zone.js/dist/zone-testing.js?:288:1)
	    at ZoneDelegate.../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/node_modules/zone.js/dist/zone.js?:387:1)
```

**Comment by vthinkxie** [comment]
@michaelkrog we are fixing it now :)

**Comment by vthinkxie** [comment]
Hi @michaelkrog 
this ci has been fixed now, would you plz rebase it, thanks!

**Comment by michaelkrog** [comment]
@vthinkxie It has been rebased now..

**Pull request merged**
