### PR TITLE
fix(module:button): fix add class ant-btn-icon-only(#7631)

### PR DESCRIPTION
**Pull request by withOutUndo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: [7631](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7631)

## What is the new behavior?
add class `ant-btn-icon-only` to button

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by sebcam** [comment]
any plan to merge this ?

**Review by hullis — COMMENTED** [review]
The code looks good to be. But a unit test would be good. :) @withOutUndo could you please add one?

**Comment by withOutUndo** [comment]
> The code looks good to be. But a unit test would be good. :) @withOutUndo could you please add one?

add some tests for this

**Review by wzhudev — APPROVED** [review]
LGTM. Thanks.

**Comment by Zaleck-a** [comment]
when would this be merged?

**Comment by wzhudev** [comment]
@simplejason This could be merged in the next patch version.

**Comment by igorbremec** [comment]
Dear developers, please merge this already 🙏 

Apps that dynamically load nz icons have been broken for a long while because of this. I've been waiting months for a fix so I can upgrade to the new version.

**Pull request merged**
