### PR TITLE
feat(module:dropdown): support arrow

### LINKED ISSUE #5386: dropdown: add nzArrow property to show an arrow

### PR DESCRIPTION
**Pull request by wendellhu95**
close #5386

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wendellhu95** [comment]
Could wait for Ant Design releasing a new minor version.

**Comment by vthinkxie** [comment]
will check this after #5414 merged

**Review by hsuanxyz — CHANGES_REQUESTED** [review]
https://preview-5387-ng-zorro-antd.surge.sh/components/dropdown/zh#components-dropdown-demo-arrow
wrong style when first opened
image

**Comment by wendellhu95** [comment]
debug 了一下，这个 bug 的原理是这样的

截屏2020-09-19 下午1 04 56

第一次打开的时候，positionChange 的事件才被 subscribe，此时 dropdown 已经弹出，之后 positionChange 事件才会导致 component 的 position 变化，又因为 markForCheck，要到下一个事件才会更新

这里的逻辑链条需要优化一下 @vthinkxie

**Pull request closed without merging**
