### PR TITLE
fix(module:breadcrumb): fix breadcrumb when Routes path=''

### PR DESCRIPTION
**Pull request by nuonuoge**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wendellhu95** [comment]
Could you please write a test to cover the case?

**Comment by nuonuoge** [comment]
It takes some time because the old test cases are not covered

**Comment by nuonuoge** [comment]
I've added test for navigate, but multiple routes in named outlets is not coverd
image

**Comment by wendellhu95** [comment]
Will close #3730.

**Comment by brice-noowu** [comment]
Is it possible that I still have the double slash problem ? See here : 
chrome_XajVlxTy0M

-------------

`dashboard-routing.module.ts` :
```typescript
const routes: Routes = [
  {
    path: '',
    component: DashboardComponent,

    children: [
      {
        path: '',
        pathMatch: 'full',
        redirectTo: 'home',
      },
      {
        path: 'home',
        loadChildren: () =>
          import('./pages/home/home.module').then((m) => m.HomeModule),
        data: {
          breadcrumb: 'Accueil',
        },
      },
      {
        path: 'workouts',
        loadChildren: () =>
          import('./pages/workouts/workouts.module').then(
            (m) => m.WorkoutsModule
          ),
        data: {
          breadcrumb: 'Sessions',
        },
      },
    ],
  },
];
```



`workouts-routing.module.ts` :
```typescript
const routes: Routes = [{ path: '', component: WorkoutsComponent }];
```

**Comment by vthinkxie** [comment]
Hi @pjurczynski 
could you open a new issue to report the issue?

**Comment by pjurczynski** [comment]
@vthinkxie I think you've mis-mentioned me ;)

**Comment by brice-noowu** [comment]
I think so, too.
I will open a new issue 👍

**Comment by nuonuoge** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/pull/5584

**Comment by brice-noowu** [comment]
@nuonuoge sorry i'm new with issuing.. So the fix hasnt been merged yet ?

**Comment by nuonuoge** [comment]
@brice-noowu It is still waiting for review

**Pull request merged**
