### PR TITLE
docs(module:carousel): add demo to use custom transition strategy

### LINKED ISSUE #6749: Add more built-in carousel transition strategy
## What problem does this feature solve?
I will add flip and transform-no-loop strategy. These will not be built-in, but could be imported via dependency injection.

## What does the proposed API look like?
NaN.

### PR DESCRIPTION
**Pull request by wendellhu95**
close #6749

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by hsuanxyz — COMMENTED** [review]
手势拖动时和导航小点不同步了

**Comment by wendellhu95** [comment]
> 手势拖动时和导航小点不同步了

好滴，我看看~

**Comment by wendellhu95** [comment]
> 手势拖动时和导航小点不同步了

具体是什么 case，我没有观察到哦

**Comment by hsuanxyz** [comment]
@wendellhu95 拖动时下面导航的小条没跟着走 

Chromium 90, Chrome 91

Screen Recording 2021-06-15 at 10 13 11 AM mov

**Comment by wendellhu95** [comment]
有点奇怪，只在测试环境出现……

**Review by hsuanxyz — APPROVED** [review]
LTGM

**Pull request merged**
