### PR TITLE
feat(module:image): now supports horizontal and vertical flip

### PR DESCRIPTION
**Pull request by ParsaArvanehPA**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [✔] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [✔] Tests for the changes have been added (for bug fixes / features)
- [✔] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[✔] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
The image component in our current version does not support horizontal and vertical flipping of the image, unlike the <a href="https://ant.design/components/image">antd</a> image component.

## What is the new behavior?
The feature of flipping the image horizontally or vertically has been implemented.

## Does this PR introduce a breaking change?
```
[ ] Yes
[✔] No
```

### CODE REVIEW

**Comment by ParsaArvanehPA** [comment]
@HyperLife1119 I would be grateful if you could review my pull request.

**Comment by HyperLife1119** [comment]
Can you resolve the conflict? I will merge it.

**Comment by ParsaArvanehPA** [comment]
> Can you resolve the conflict? I will merge it.

Yeah sure,
Thanks @HyperLife1119.
 
I have 2 more branches that have conflicts and have `PR: reviewed-approved` tag that haven't been merged; should I notify you after I resolve those two branches too?

**Comment by HyperLife1119** [comment]
absolutely okay! @ParsaArvanehPA

**Comment by ParsaArvanehPA** [comment]
@HyperLife1119 

https://github.com/NG-ZORRO/ng-zorro-antd/pull/8180
https://github.com/NG-ZORRO/ng-zorro-antd/pull/8283

These are the two branches with conflicts I mentioned earlier, thanks in advance.

**Comment by ParsaArvanehPA** [comment]
Thank you for checking this pr @HyperLife1119

https://github.com/NG-ZORRO/ng-zorro-antd/pull/8180
https://github.com/NG-ZORRO/ng-zorro-antd/pull/8283

These are the two branches with conflicts I mentioned earlier, thanks in advance.

**Pull request merged**
