### PR TITLE
feat: add provide function

### PR DESCRIPTION
**Pull request by MunMunMiao**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #7953

## What is the new behavior?

See: #7953

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by HyperLife1119** [comment]
I think `provideNz` or `provideNgZorro` or `provideZorro` will be better naming.

Because it does not rule out that we will have such a function signature:
```ts
provideNz(
  config,
  withAFeature(),
  withAFeature()
)
```

In other words, not only configurations can be added here.

**Comment by MunMunMiao** [comment]
> I think `provideNz` or `provideNgZorro` or `provideZorro` will be better naming.
> 
> Because it does not rule out that we will have such a function signature:
> 
> ```ts
> provideNz(
>   config,
>   withAFeature(),
>   withBFeature()
> )
> ```
> 
> In other words, not only configurations can be added here.

This proposal is based on the package dimension. 

like:

> @angular/common/http

[provideHttpClient](https://angular.io/api/common/http/provideHttpClient)

> @angular/platform-browser

[provideClientHydration](https://angular.io/api/platform-browser/provideClientHydration)

> @angular/platform-browser/animations

[provideAnimations](https://angular.io/api/platform-browser/animations/provideAnimations)
[provideNoopAnimations](https://angular.io/api/platform-browser/animations/provideNoopAnimations)

[API List](https://angular.io/api?query=provide) more...

**Comment by MunMunMiao** [comment]
@simplejason 你好，麻烦看下这个PR是否可以合入。

**Comment by simplejason** [comment]
目前有可能保留原有的使用方式但标注 deprecated 吗？看上去用户升级后会出现 break change

**Comment by MunMunMiao** [comment]
> 目前有可能保留原有的使用方式但标注 deprecated 吗？看上去用户升级后会出现 break change

现在只是提供了一系列provide*的function，原使用方式目前不影响，provide*的函数是为了日后取消了module而做准备

**Comment by HyperLife1119** [comment]
这里不会出现 breaking change，我们应该移除这个 label 😊

**Comment by Laffery** [comment]
@MunMunMiao  provide function 和原来的使用方式是等价的，我觉得 `ng-add` schematic 现在应该可以默认生成 provide function 形式的代码了

**Pull request merged**
