### PR TITLE
no need to fix moment. introduce moment in right way

### PR DESCRIPTION
**Pull request by LinBoLen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #85 #169 #240

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by LinBoLen** [comment]
it seems that it will cause typescript lint error in angular cli project.
but we can superress the error

**Comment by vthinkxie** [comment]
@trotyl any idea?

**Comment by trotyl** [comment]
This would require user to have `allowSyntheticDefaultImports` on their own `tsconfig`, would be a breaking change (even is small).

**Comment by trotyl** [comment]
@LinBoLen Can you provide what your error is, working fine in my local env and CI.

**Comment by trotyl** [comment]
Another issue is that `default` auto-fallback it not available in closure compiler, even we didn't officially support it now, it should be considered for all Angular library (in not introducing compatibility issue deliberately).

**Comment by LinBoLen** [comment]
- never mind the lint error, it comes from webstorm default typescript service, this is just one of thousand lint error.
- `allowSyntheticDefaultImports ` is used for developer work on ng-zorro-antd.  no user
- closure compiler auto-fallback without `allowSyntheticDefaultImports` in typescript

**Comment by trotyl** [comment]
The `.d.ts` is provided along with the library distribution, it would show TypeScript error for no default export, unless user also have set `allowSyntheticDefaultImports` in their `tsconfig`.

`allowSyntheticDefaultImports` would not change generated result, and closure didn't care about `.d.ts` at all, whatever set in `tsconfig` won't help.

**Comment by trotyl** [comment]
You can have a look of [official usage](https://github.com/angular/material2/blob/master/src/material-moment-adapter/adapter/moment-date-adapter.ts#L17-L19), namespace export are always required (as long as we don't want to break user), and our in-build process is much simpler than this. (And it's OK since we just have one library)

**Comment by trotyl** [comment]
I guess you may have some misunderstandings about `allowSyntheticDefaultImports`.

`allowSyntheticDefaultImports` is a type-checking specific option (like `allowUnusedLabels` or `noImplicitAny`), only defines the type-checking rule, results in no change of generated files (none of `.js`, `.d.ts` or `.map` would be affected).

This kind of options have no propagation behavior, even if it compiles in your workspace, does not mean it can work in it's consumers'. (eg. `https://github.com/angular/angular/issues/17863`, `https://github.com/angular/angular/issues/17522`, or `https://github.com/angular/angular/issues/17800`, not want to pollute them so didn't use links) 

What you need may be covered in `https://github.com/Microsoft/TypeScript/issues/16093`.

**Comment by LinBoLen** [comment]
but it seems that just use `import moment from moment`. it works

**Comment by trotyl** [comment]
That's because currently we don't have any type dependency of the namespace import.

You can try with:

```typescript
import * as moment from 'moment';
export const t = moment();
```

Then the generated `.d.ts` file will be:

```typescript
import * as moment from 'moment';
export declare const t: moment.Moment;
```

So that our way of importing would be propagated to our consumers.

In `moment.d.ts`, there're hundred of types, once any of them be used implicitly in our code, the users will be break.

**Comment by trotyl** [comment]
I suggest that just making the same Pull Request to `material2` and they can answer it better (if they want).

**Pull request closed without merging**
