### PR TITLE
refactor(module:all): remove property for static host className

### LINKED ISSUE #649: perf: no property for static className
## What problem does this feature solve?

Currently we're using `@HostBinding()` even for static className, like:

```typescript
class Tmp {
  @HostBinding(`class.ant-prop`) _prop = true;
}
```

The generated checking will be:

```typescript
var currVal_0 = jit_nodeValue_6(_v,1).prop;
_ck(_v,0,0,currVal_0);
```

The property will leave in runtime and being checked in each change detection.

Changing it to:

```typescript
@Component({
  host: {
    '[class.ant-prop]': 'true'
  }
})
class Tmp {}
```

Which generates:

```typescript
var currVal_0 = true;
_ck(_v,0,0,currVal_0);
```

The metadata will be removed in production for the sake of build-optimizer, which will leave no extra loads. 

## What does the proposed API look like?

N/A.

### PR DESCRIPTION
**Pull request by trotyl**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: closes #649

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by trotyl** [comment]
Coverage rate decreased due to removal of already covered property, didn't affect real coverage.

```
x - 1   x
----- < -
y - 1   y     (x > 1, y > 1)
```

**Comment by vthinkxie** [comment]
seems conflict with https://github.com/NG-ZORRO/ng-zorro-antd/pull/459

**Comment by trotyl** [comment]
Confirmed, will solve it

**Comment by trotyl** [comment]
CI failure due to rebased to current master, will rebase again after #679.

**Pull request merged**
