### PR TITLE
refactor: removed all usages of <color-sketch>

### PR DESCRIPTION
**Pull request by ParsaArvanehPA**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently there are 2 usages of an external library called `color-sketch` in our codebase; one in the Watermark component, and another one in the footer of the doucment site.

## What is the new behavior?
Removed all usages of `color-sketch` and use Ng-zorro's built-in color picker.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Usages:

image

### CODE REVIEW

**Review by OriginRing — APPROVED** [review]

**Comment by Laffery** [comment]
Hi @ParsaArvanehPA , thanks to your nice contribution, I submit some suggesions to remove useless styles and I hope this message finds you well :)

**Comment by ParsaArvanehPA** [comment]
> Hi @ParsaArvanehPA , thanks to your nice contribution, I left some suggesions to remove useless styles and I hope this message finds you well :)

Hi @Laffery , thank you for checking my PR.
I think you forgot to submit your reviews because I don't see any requested changes.

**Comment by Laffery** [comment]
> Hi @Laffery , thank you for checking my PR. I think you forgot to submit your reviews because I don't see any requested changes.

I'm sorry about that, it's available now

**Comment by ParsaArvanehPA** [comment]
> > Hi @Laffery , thank you for checking my PR. I think you forgot to submit your reviews because I don't see any requested changes.
> 
> @ParsaArvanehPA I'm sorry about that, it's available now

Changes have been made, thanks again for checking it out @Laffery

**Pull request merged**
