### PR TITLE
docs(showcase): add note to `textarea`

### PR DESCRIPTION
**Pull request by tigercosmos**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

Add note on `textarea` showcase in `nzInput`. Let the description be more complete.

r? @vthinkxie

### CODE REVIEW

**Comment by wilsoncook** [comment]
@tigercosmos More better to add the usage of `nzRows` parameter under the API section, could you?

**Comment by tigercosmos** [comment]
I think we can add at both "showcase" and "API ". We usually read showcase first, and go to read API if something are not clear.
How do you think?

**Comment by wilsoncook** [comment]
Yeah, provide more info. of usage about `nzRows` below in API is better

**Comment by tigercosmos** [comment]
sure

**Comment by tigercosmos** [comment]
thanks

**Pull request merged**
