### PR TITLE
fix(module:carousel): fix carousel under rtl

### PR DESCRIPTION
**Pull request by wendellhu95**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wendellhu95** [comment]
@hsuanxyz 我看了一下 React 版本，carousel 的滚动方向还是不变的，这里好像不太需要改 transform strategy

**Comment by hsuanxyz** [comment]
> @hsuanxyz 我看了一下 React 版本，carousel 的滚动方向还是不变的，这里好像不太需要改 transform strategy

问题就是 React 的动画 ltr，但是下面的导航条是 rtl。可以参考一下

[RTL Demo | Owl Carousel | 2.3.4](https://owlcarousel2.github.io/OwlCarousel2/demos/rtl.html) 
[Carousel](https://bootstrap.rtlcss.com/docs/4.0/components/carousel/)

**Comment by hsuanxyz** [comment]
@wendellhu95 还有一个问题是 React 在使用**手势**时和**点击导航条**的方向是反的

**Review by hsuanxyz — APPROVED** [review]
LGTM, 先这样和 React 保持一致吧，免得样式同步起来麻烦

**Pull request merged**
