### PR TITLE
feat(module:time-picker): support 12-hour with `nzUse12Hours`

### PR DESCRIPTION
**Pull request by kekehaoz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
TimePicker support 12-hour

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1513 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by TheAifam5** [comment]
Would not be better to handle it like “nzConvention=‘12’” and “nzConvention=‘24’”?

**Comment by kekehaoz** [comment]
> Would not be better to handle it like “nzConvention=‘12’” and “nzConvention=‘24’”?
To  keep same with Ant Design of React

**Comment by kekehaoz** [comment]
> Would not be better to handle it like “nzConvention=‘12’” and “nzConvention=‘24’”?

To keep same with Ant Design of React

**Comment by patricknazar** [comment]
Thank you @wilsoncook !

**Comment by wilsoncook** [comment]
All thanks to @kekehaoz

**Comment by patricknazar** [comment]
My mistake, thanks @kekehaoz !!

**Pull request merged**
