### PR TITLE
feat(site): add two ways to compile target demo when running start

### PR DESCRIPTION
**Pull request by orzyyyy**
## PR Type

Imporve compiling site.

## How to use

Suppose the demo you want to compile is `button/demo/ghost.md`, then

1. run command `npm run start button/demo/ghost.md`

2. add `only: true` at the top, which is called `metadata`, as below,
```bash
---
only: true
order: 8
title:
  zh-CN: 幽灵按钮
  en-US: Ghost Button
---
```

### CODE REVIEW

**Comment by orzyyyy** [comment]
深度截图_选择区域_20190729122445

**Comment by orzyyyy** [comment]
Any progress?

**Comment by wendzhue** [comment]
It's not a good idea to write

``` yaml
only: true
```

Better to make a parameter of command `npm run start`, like `npm run start button`.

**Comment by orzyyyy** [comment]
CI won't pass if any commit contains `only`, so I think it doesn't matter.

**Comment by wendzhue** [comment]
> CI won't pass if any commit contains `only`, so I think it doesn't matter.

CI takes time. And developers still needs to add a commit for remove that line.

**Comment by orzyyyy** [comment]
OK, I'll add a check before commit.

**Comment by orzyyyy** [comment]
Now you can run `npm start button/demo/ghost.md` to compile that one.

**Comment by orzyyyy** [comment]
Ping~

**Comment by wendzhue** [comment]
@hsuanxyz Have time to review this?

**Pull request closed without merging**
