### PR TITLE
feat(module:*): support for Angular ivy

### PR DESCRIPTION
**Pull request by hsuanxyz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #3667

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by lppedd** [comment]
Seems `date-fns` isn't compatible with NGCC, and it's a direct dependency. What a pity.

**Comment by lppedd** [comment]
@hsuanxyz So, I was able to compile `date-fns` using a custom `ngcc.config.js` file.

However there is still a problem with deep imports (https://github.com/angular/angular/issues/32097).  
The next `next.3` version will include a fix and maybe I'll finally be able to compile my project, even without `ng-zorro` explicitly targeting `Ivy`.

**Comment by lppedd** [comment]
`next.4` introduces a fix to avoid scanning non-Angular dependencies for entry points.  
The `ngcc.config.js` is no more needed.

**Comment by hsuanxyz** [comment]
close via #4453

**Pull request closed without merging**
