### PR TITLE
fix(module:timeline): when the data clear, reset items

### PR DESCRIPTION
**Pull request by to0simple**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by to0simple** [comment]
#7030

**Comment by wendellhu95** [comment]
Hi. Thanks for this PR. Could you please add a test to ensure code coverage?

**Comment by to0simple** [comment]
> Hi. Thanks for this PR. Could you please add a test to ensure code coverage?

I've added a test.

**Review by wendellhu95 — APPROVED** [review]
LGTM

**Pull request merged**
