### PR TITLE
feat(module:core): make no-animation standalone

### PR DESCRIPTION
**Pull request by Nicoss54**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

NzNoAnimation Directive is not standalone

Issue Number: N/A

## What is the new behavior?

NzNoAnimation Directive is standalone and NzNoAnimationModule is replaced in component library

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by Nicoss54** [comment]
@HyperLife1119 does it looks good to you ?

**Comment by HyperLife1119** [comment]
I need to wait for other components to complete the standalone transformation before I come back to check this. Because too many changes have occurred in the meantime.

**Comment by Nicoss54** [comment]
> I need to wait for other components to complete the standalone transformation before I come back to check this. Because too many changes have occurred in the meantime.

That’s made totally sens. I will rebase the other pr on implémentation  new code flow on doc snippet and merge it, if you’re ok. Need this or to continue my work on the other components

**Comment by HyperLife1119** [comment]
This appears to be a duplicate of #8265. If you have no problem, I will close this PR :)

**Comment by HyperLife1119** [comment]
This PR is related to #8265.

**Comment by Nicoss54** [comment]
> Can you resolve the conflict :)

Of course. Will do it during the day

**Review by HyperLife1119 — APPROVED** [review]
LGTM

**Pull request merged**
