### PR TITLE
fix(module:select): icons not showing multi (#5575 #5568)

### LINKED ISSUE #5575: Why is show arrrow not avaible on multi or tag select
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-ppxcmt](https://stackblitz.com/edit/ng-zorro-antd-ivy-ppxcmt)

### Steps to reproduce
Open the link.
The first select has an arrow icon and a search icon when you open the select.

The second select is a multi-select and doesn't have an arrow icon.
While I added the `[nzShowArrow]` and set it on `true`. 
In the documentation, there is no mention that the arrow icon doesn't work in multi-select mode.

### What is expected?
That I see the arrow icon in multi-select

### What is actually happening?
No arrow icon in multi-select

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.3.0 |
| Browser | Firefox Developer version 79.0b8 (64-bits), Firefox version 79.0b8 (64-bits), Google Chrome Version 84.0.4147.89 (64-bit)  |

---
`[nzShowSearch]` isn't also working in multi-select but that's mentioned in the documentation, but would it be possible to make it aviable in multi-select? If no, can you explain what the reason behind this choice is?

### PR DESCRIPTION
**Pull request by DepickereSven**
close #5575 #5568

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #5575 and #5568 

## What is the new behavior?

Arrow icon and search icon can be used in multi mode

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by DepickereSven** [comment]
@vthinkxie 

Some screenshots to prove that it works

Screenshot_2020-09-08 NG-ZORRO - Ant Design Of Angular(1)
Screenshot_2020-09-08 NG-ZORRO - Ant Design Of Angular

**Comment by vthinkxie** [comment]
Hi @DepickereSven 

按照 ant design 设计规范，在多选模式下是没有下拉箭头的，在 9.x 之后同步了 antd 4.x 的设计规范，因此多选箭头被移除了，这是在预期中的，不是一个bug

感谢你的 PR

**Comment by DepickereSven** [comment]
@vthinkxie 

By ant-design are you referring to this library https://github.com/ant-design/ant-design/? 

Because when I look in their docs I find the following:

Schermafbeelding 2020-09-15 om 11 51 16

So for multi-select and tags is by default on false. But it's possible to set the showArrow on true so you can see it.

Like you can see in the following example the icons work in multi and tag mode.

https://stackblitz.com/edit/react-vrppip?file=index.js

**Comment by Hx2heng** [comment]
> Hi @DepickereSven
> 
> 按照 ant design 设计规范，在多选模式下是没有下拉箭头的，在 9.x 之后同步了 antd 4.x 的设计规范，因此多选箭头被移除了，这是在预期中的，不是一个bug
> 
> 感谢你的 PR

在多选模式下，设置nzShowArrow为true没有箭头出现。（ng-zorro 版本9.3.0）

**Comment by DepickereSven** [comment]
@Hx2heng 

This has been solved in the following PR  #5785.
This PR is included in version 10.0.0.
So it's normal that it doesn't work in 9.3.0.

So to get this bug solved I would suggest you upgrade to Angular 10. So you can use ng-zorro 10.0.0.
Changelog of version 10.0.0 => https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/10.0.0

**Comment by Hx2heng** [comment]
@DepickereSven Thanks.

**Comment by zds-d** [comment]
In version 10.x, tree-select component already has nzShowArrow property, but nz-tree-select component still does not have this property

**Pull request closed without merging**
