### PR TITLE
fix(module:date-picker): fix disable time when date changes

### LINKED ISSUE #5335: nz-range-picker 根据给定的date time range来disable日期和时间
### Reproduction link
[https://codesandbox.io/s/ng-zorro-antd-ivy-v3urf?file=/src/app/app.component.ts](https://codesandbox.io/s/ng-zorro-antd-ivy-v3urf?file=/src/app/app.component.ts)

### Steps to reproduce
1. Click range picker start time.
2. Click 16th of May,

### What is expected?
Hour from 0 to 16 should be disabled.

### What is actually happening?
Hour not disabled until I click 17 in hour column.

| Environment | Info |
|---|---|
| ng-zorro-antd | 9.1.2 |
| Browser | Chrome |

---
I need to disable date and time outside the range below:
change_time_start = 2020-05-16T17:51:59.963Z
change_time_end = 2020-05-23T17:52:03.155Z

The code I provide is trying to disable hours and mins at "Start Time" only. It seems that change in date will not disable hour/min/sec dynamically.

### LINKED ISSUE #7069: nz-date-picker disabled time doesn't get refreshed on date change
### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-ivy-zj7sta?file=src/app/app.component.ts](https://stackblitz.com/edit/ng-zorro-antd-ivy-zj7sta?file=src/app/app.component.ts)

### Steps to reproduce
By default today's date and time is set in date picker.
I have disabled past hours and minutes for today's date (Simply want to restrict user from selecting past date and time)

1. Select future date (e.g. tomorrow)
2. Observe time

### What is expected?
It should enable/disable as soon as we change date.

### What is actually happening?
Time component is not getting refreshed on date change

| Environment | Info |
|---|---|
| ng-zorro-antd | 12.0.2 |
| Browser | Google Chrome/Microsoft edge |

---
Probably change detection should be triggered for time component on date change. Which I am unable to do as I can't get instance of time component.

### PR DESCRIPTION
**Pull request by AdvanceOrange**
close #7069, close #5335

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #7069, #5335 

## What is the new behavior?
Update the time status when the date changes

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wenqi73** [comment]
@AdvanceOrange Sorry for the late reply, could you add the unit test about this? See https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/date-picker/date-picker.component.spec.ts as a reference.

**Comment by AdvanceOrange** [comment]
Okay.&nbsp;All right.&nbsp;I'll try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NG-ZORRO/ng-zorro-antd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NG-ZORRO/ng-zorro-antd] fix(module:date-picker): fix disable time when date changes (PR #7236)





 
@AdvanceOrange Sorry for the late reply, could you add the unit test about this? See https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/date-picker/date-picker.component.spec.ts as a reference.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AdvanceOrange** [comment]
@wenqi73 Hi, I've added the unit test code

**Review by wenqi73 — APPROVED** [review]
LGTM. @AdvanceOrange good job!

**Pull request merged**
