### PR TITLE
fix(module:tree): fix search case sensitivity

### PR DESCRIPTION
**Pull request by krokofant**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1996 #4765 

## What is the new behavior?
1. Will search in a case insensitive manner
2. Will highlight in a case insensitive manner

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by purplesoft-io** [comment]
please merge this commit...

**Comment by simplejason** [comment]
Thanks for your PR, we will review it ASAP, please make sure you have rebased with master and added tests :)

**Comment by krokofant** [comment]
@simplejason I'll try to remember this for monday. Thanks for the feedback.

**Comment by krokofant** [comment]
@simplejason Awaiting your review :-)

**Comment by krokofant** [comment]
@vthinkxie Could you review these changes?

**Pull request merged**
