### PR TITLE
fix(module:message): adjust long number line feeds (#8332)

### PR DESCRIPTION
**Pull request by chongchongLin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

[](https://github.com/NG-ZORRO/ng-zorro-antd/issues/8332)
Issue Number: 8332

## What is the new behavior?
Automatic line feeds for long numbers

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by Nicoss54 — APPROVED** [review]
LGTM

**Comment by HyperLife1119** [comment]
Sorry, this style is not in the ant design specification, and the issue also exists in ant.design and we cannot merge it.
In general, you should not use the message component when you need to display long text.

**Comment by chongchongLin** [comment]
> 抱歉，ant design 规范中没有这个样式，ant.design 中也存在这个问题，我们无法合并。 一般来说，当需要显示长文本时，不应该使用消息组件。
> 
> 如果你同意的话，我就关闭这个。@Nicoss54

I found this problem precisely because our system's unified error handling uses NzMessage, and now the current solution does use NzModal, so will this problem be solved in the future?

**Comment by HyperLife1119** [comment]
Our style specifications need to be consistent with ant.design. Only when ant.design thinks this is a problem and fixes it, we will synchronize the fix.

**Comment by Nicoss54** [comment]
> Sorry, this style is not in the ant design specification, and the issue also exists in ant.design and we cannot merge it. In general, you should not use the message component when you need to display long text.
> 
> If you're okay with that, I'll close this. @Nicoss54

Yes, we can close it. That’s why I put the partially approved tag, because we had to discuss it. 

I will close it

**Pull request closed without merging**
