### PR TITLE
chore: bump to angular 16.2

### PR DESCRIPTION
**Pull request by Nicoss54**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

Bump to last angular version

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Ng-Zorro is on Angular 16.0.0 version

Issue Number: N/A

## What is the new behavior?

Ng Zorro is on the last version of Angular

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by simplejason** [comment]
Please rebase with master, after that, I will merge it and release a new version for angular v16.2.0

**Comment by Nicoss54** [comment]
> Please rebase with master, after that, I will merge it and release a new version for angular v16.2.0

@simplejason it's done, thanks for the review

**Comment by Nicoss54** [comment]
@simplejason can we merge this PR, to prepare slowly the next big major version of Angular ?

**Comment by Nicoss54** [comment]
@OriginRing is it possible to merge this PR, we need it as a partial migration version of Angular to prepare the migration to Angular 17. 

Then we also have to accept https://github.com/NG-ZORRO/ng-zorro-antd/pull/8095 because new project with Angular cli will create a standalone app by default

**Review by OriginRing — APPROVED** [review]

**Comment by OriginRing** [comment]
LGTM

**Pull request merged**
