### PR TITLE
fix(module:drawer): remove inline style to resolve CSP issue

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by HyperLife1119** [comment]
We should remove `--scroll-bar` from the drawer component because I can't find any code that is using it.

**Comment by arturovt** [comment]
> We should remove `--scroll-bar` from the drawer component because I can't find any code that is using it.

Updated.

**Review by Nicoss54 — CHANGES_REQUESTED** [review]
Thanks for the work, is it possible to make pass the job failed please ?

After that LGTM

**Review by Nicoss54 — APPROVED** [review]
LGTM

**Pull request merged**
