### PR TITLE
feat(module:modal): Remove nzComponentParams in v16

### PR DESCRIPTION
**Pull request by MunMunMiao**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #7827

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

### CODE REVIEW

**Comment by Nicoss54** [comment]
LGTM :)

**Comment by Nicoss54** [comment]
@MunMunMiao could you rebase your branch ?

**Comment by MunMunMiao** [comment]
> @MunMunMiao could you rebase your branch ?

ok. done

**Review by simplejason — APPROVED** [review]
LGTM

**Pull request merged**
