### PR TITLE
[bug] fix picker icon click noting when isRange is false

### PR DESCRIPTION
**Pull request by lopn**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

date-picker  when isRange is false ,  click the icon  the overlay is not show  

Issue Number: #2027 

## What is the new behavior?
data-picker click the icon trigger event  (onClickInputBox) , then show then overlay

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Comment by smile2014** [comment]
import { Component, ViewChild } from '@angular/core';
import {ICellEditorAngularComp} from "ag-grid-angular";
import { dateFormat } from '../../../utils/utils';
import { NzDatePickerComponent } from '@nz-antd-zorro';

@Component({
    selector: 'apes-cell-select-input',
    template: `
      <nz-date-picker #picker (keydown)="onKeyDown($event)" [(ngModel)]="inputValue"  (ngModelChange) = "onChange($event)"></nz-date-picker>
     `,
    styles: []
})
export class EditorDateComponent implements ICellEditorAngularComp {
    inputValue: any;
    params: any;
    ctx: any;
    formatType: string = 'yyyy-MM-dd';

    @ViewChild('picker', {read: NzDatePickerComponent}) picker: NzDatePickerComponent;

    constructor() {
    }

    agInit(params: any): void {
        this.params = params;
        // this.api = params.api;
        // this.downFormatter = params.downFormatter;
        // this.valueFormatter = params.valueFormatter;
        console.log(params);
        this.inputValue = params.value;
        this.ctx = params.context;

    }

    ngAfterViewInit() {
      //this.picker.apesOpen = true;
    }
    isPopup(): boolean {
        return true;
    }


    getValue(): any {
        let result;
        if (!this.inputValue) {
            result = '';
            this.params.value = '';
        } else {
            result = this.inputValue;
            this.params.value = this.inputValue;
        }
        return result;
    }

  onKeyDown(event): void {
    let key = event.which || event.keyCode;
    if (key === 38 || key === 40) {
      this.preventDefaultAndPropagation(event);
    }else if (key == 13 || key == 9) { // enter
      // perform some validation on enter - in this example we assume all inputs are mandatory
      // in a proper application you'd probably want to inform the user that an input is blank'
      /**/
      this.inputValue = event.target.value
      this.params.value = event.target.value;
    }
  }
  onChange(param){
    this.inputValue = dateFormat(this.formatType, new Date(param));
    this.params.value = this.inputValue;
  }
  private preventDefaultAndPropagation(event) {
    event.preventDefault();
    event.stopPropagation();
  }
}

没办法集成在ag-grid里

**Comment by smile2014** [comment]
日期组件集成在表格下，点击下一个月就关闭了当前面板

**Comment by smile2014** [comment]
日期组件集成在表格下，点击下一个月就关闭了当前面板
https://stackblitz.com/edit/angular-grid-zorro

**Comment by smile2014** [comment]
@HsuanXyz  @wilsoncook 
日期组件集成在表格下，点击下一个月就关闭了当前面板
https://stackblitz.com/edit/angular-grid-zorro

**Comment by vthinkxie** [comment]
Due to no progress for a long time, this issue will be closed. Please contact us if you have any questions.

**Pull request closed without merging**
