### PR TITLE
docs(module:tooltip): more use is directive type

### PR DESCRIPTION
**Pull request by DreamPWJ**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wendzhue** [comment]
@DreamPWJ 这些组件都是同时支持 directive 和 component 用法的

**Comment by DreamPWJ** [comment]
> @DreamPWJ 这些组件都是同时支持 directive 和 component 用法的

指令用法比较多，如果同时支持是否考虑两个标签都显示？

**Comment by hsuanxyz** [comment]
@wendzhue 没问题, 默认使用指令，组件存在的意义是兼容，未来可能弃用

**Comment by wendzhue** [comment]
> @wendzhue 没问题, 默认使用指令，组件存在的意义是兼容，未来可能弃用

Deprecate 的话可以用个 warning 声明一下。

**Pull request merged**
