### PR TITLE
fix:(module: date-picker): dd.MM.yyyy date format

### PR DESCRIPTION
**Pull request by danielszenasi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

I want to use the date-picker with the following format [nzFormat]="'dd.MM.yyyy'", when I type the picker`s input, the state does not change, because the javascript date creates Wed Mar 07 2018 00:00:00 GMT+0100 (Central European Standard Time) from this string: "03.07.2018", so the day and mounth is not the correct order for the Date object.

Issue Number: N/A

## What is the new behavior?
[nzFormat]="'dd.MM.yyyy'" works

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by vthinkxie** [comment]
Hi @danielszenasi thanks for you pr!
I think there maybe some methods to support more format types including `dd/MM/yyyy`.

@wilsoncook please check this.

**Comment by danielszenasi** [comment]
Thanks for your response, i will try to provide a better solution later.

**Comment by smile2014** [comment]
Date assignment in the frame interface is null, but parsed into {}

**Comment by TheAifam5** [comment]
I would prefer a interface with date time formatter with two functions:
parseDate
firmatDate

So everyone can use what the framework of own choice.

**Comment by orlandokj** [comment]
@wilsoncook there is a reason for removing momentjs? I'm thinking about to fix this bug, and the faster way is to use momentjs.

**Comment by irishwill2008** [comment]
I am having similar issue, I am trying to implement: `<nz-date-picker nzFormat="dd/MM/yyyy"></nz-date-picker>` however when i type in "07/07/2019" it does not recognise. Similar to the `dd.MM.yyyy` issue.

Did anyone find an easy work around or?

**Comment by vthinkxie** [comment]
Since there is no reply for a long time, this issue will be closed. Please contact us if you have any questions, thank you for your PR

**Comment by TheAifam5** [comment]
@irishwill2008 you mean something like that issue: https://github.com/NG-ZORRO/ng-zorro-antd/issues/3491

**Pull request closed without merging**
