### PR TITLE
docs(spin): fix api table format

### PR DESCRIPTION
**Pull request by SangKa**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

In the demo of spin, the description column of the API table should after the property column for unification.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
About the Enum type, there are three types representation in the docs.
  * String
  * 'blue' | 'red' | 'green'
  * Enum (only in the spin demo)

The first two are common, I suggest to make them uniform and I can do once you make the decision.

### CODE REVIEW

**Comment by vthinkxie** [comment]
could not be named as a doc fix. closed

**Comment by SangKa** [comment]
any guide or suggestion?

**Comment by vthinkxie** [comment]
thanks for your pr, but change doc's order is not meaningful enough as a pr.

**Comment by SangKa** [comment]
got it

**Pull request closed without merging**
