### PR TITLE
build: enable ivy lib

### PR DESCRIPTION
**Pull request by vthinkxie**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by JoostK** [comment]
Heya, thanks for running this experiment! I took a brief look at the Azure job and I'm surprised by the Babel transform errors that occur; we'll definitely have to look into what's going on there.

**Comment by JoostK** [comment]
Quick update: we have figured out why it's failing and it requires a fix in the linker; this will hopefully make it into next week's patch release.

**Comment by JoostK** [comment]
Or even better: it's now been fixed and will release later this week (usually Wednesday's)

**Comment by vthinkxie** [comment]
thanks @JoostK

**Comment by JoostK** [comment]
Angular FW 11.1.1 is out, could you please give that a spin? 🚀

**Comment by vthinkxie** [comment]
> Angular FW 11.1.1 is out, could you please give that a spin? 🚀

it seems everything works fine now, thanks!

**Pull request closed without merging**
