### PR TITLE
fix(module:select, datepicker, timepicker, radio, checkbox, input-number) fix touched state

### PR DESCRIPTION
**Pull request by deart1mer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A
#228 

## What is the new behavior?
Fix these module:
- select
- datepicker
- timepicker
- radio
- checkbox
- input-number

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by vthinkxie** [comment]
please keep the commit history clean, thanks.

**Comment by vthinkxie** [comment]
please remove the commit log of Merge branch 'master' into fix-touched-state
you can use squash option to remove it.

**Comment by deart1mer** [comment]
Sorry for that, it took me some time to figure it out how to do that. Now is it all right?

**Comment by vthinkxie** [comment]
Yes

**Pull request merged**
