### PR TITLE
feat(module: carousel): `nzLoop` to prevent the carousel to go in a loop

### PR DESCRIPTION
**Pull request by yurica7**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #7652 
close: #7652 

## What is the new behavior?

Set `[nzLoop] = "false"` can prevent the carousel to go in a loop, for example when we are on the last item and swipe it right it should stay there, not going on the first item.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by hullis** [comment]
LGTM. Thanks!

**Comment by hullis** [comment]
It seems that codecov requirement is unmet. Please add more test code to improve code coverage. Appreciate it!

**Comment by yurica7** [comment]
> It seems that codecov requirement is unmet. Please add more test code to improve code coverage. Appreciate it!

Now it seems that the CI has passed.

**Review by hullis — APPROVED** [review]
LGTM. Thanks! This will be merged into the master branch before the next minor version release. cc @simplejason

**Pull request merged**
