### PR TITLE
fix(module:carousel): slide switching issue #2218

### PR DESCRIPTION
**Pull request by wanpeng2008**
to fix issues: #2218, also #2014
the switch action is implemented by animation instead of transform,
test case carousel ‘should effect change work’ is temporarily pending

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #2218 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information
the switch action is implemented by animation instead of transform,
the current test case carousel ‘should effect change work’  will fail because the transform attribute is no longer used.
Now this case is temporarily bypassed by xit.

### CODE REVIEW

**Comment by wendzhue** [comment]
@wanpeng2008 Please format your code to pass CI. Click the Details button for more details.

And you should add a test case.

**Comment by wendzhue** [comment]
@wanpeng2008 Hi. Are you still working on this? I am refactoring this component and if you loose interest in this I can take it over. Thanks.

**Comment by wanpeng2008** [comment]
@wendzhue Thanks for your support. I am sorry for the failed submit.

**Comment by vthinkxie** [comment]
@wendzhue has submitted pr, close now

**Pull request closed without merging**
