### PR TITLE
fix(module:input): fix type error

### PR DESCRIPTION
**Pull request by deart1mer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A
#282 

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by vthinkxie** [comment]
duplicated #271 and it is not a bug but a hack.

**Comment by deart1mer** [comment]
@vthinkxie  Got it. 
But I think it's hard to accept an error when running `npm run start` to develop.
It could be handled like `disabled` attribute in form element. If it it an attribute, no matter what the value is true. If it is set to a type of `boolean` or `AutoSizeType` as an input value, match the `boolean | AutoSizeType` type.

Such like this:

```ts
  set nzAutosize(value: string | boolean | AutoSizeType) {
    if (typeof value === 'string') {
      this._autosize = true;
    } else {
      this._autosize = <boolean | AutoSizeType>value;
    }

    if (this._autosize) {
      this._render.setAttribute(this.nativeElement, 'autosize', '');
    } else {
      this._render.removeAttribute(this.nativeElement, 'autosize');
    }
  }
```

Is that a good way?

**Comment by vthinkxie** [comment]
@deart1mer yes, but it is strange that there is no error when I run npm run start.
You can change it as your newest code if it can fix your environment.

**Comment by deart1mer** [comment]
@vthinkxie OK :-)

**Comment by thegatheringstorm** [comment]
😄  I thought I was the only one who ran into this bug before this PR....

**Comment by LinBoLen** [comment]
btw, I think autosize is ambiguity.

**Pull request merged**
