### PR TITLE
fix(module:carousel): not adapting to new size when resizing

### PR DESCRIPTION
**Pull request by ParsaArvanehPA**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [✔] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[✔] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Carousel component currently does not adapt to the new size when it is resized.

Issue Number: #8359 

## Does this PR introduce a breaking change?
```
[ ] Yes
[✔] No
```

## Other information
I have set a 100ms delay for the the debounceTime, so the `this.layout()` method does not fire so often; but I am not sure as to what is the best value for dueTime of debounceTime.

### CODE REVIEW

**Review by Nicoss54 — CHANGES_REQUESTED** [review]
Please could you provide test for the code you added ?

**Comment by ParsaArvanehPA** [comment]
> Please could you provide test for the code you added ?

Sure, I will get back to you with that as soon as I can.

**Comment by ParsaArvanehPA** [comment]
> Please could you provide test for the code you added ?

Sorry for the delay; tests for the changes have been added. 
Thank you for reviewing my PRs @Nicoss54

**Review by Nicoss54 — APPROVED** [review]
LGTM

**Pull request merged**
