### PR TITLE
fix: inline external css

### PR DESCRIPTION
**Pull request by HyperLife1119**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #8119 #8106

## What is the new behavior?

我们不能通过简单的删除 `~` 符号来修复这一问题：

```less
@import '~@angular/cdk/overlay-prebuilt.css';
```

修改为

```less
@import '@angular/cdk/overlay-prebuilt.css';
```

这会导致 ZORRO 文档构建失败，因为编译器将该路径视为本地路径，而非外部依赖路径（node_modules）。

此修改通过使用 `@import (inline)` 内联导入语句，将外部 CSS 直接内联到文件，解决上述问题。

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Nicoss54** [comment]
LGTM

**Comment by ramoverflow** [comment]
angular 16 @angular-devkit/build-angular:browser
overlay-prebuilt.css not found.

**Comment by HyperLife1119** [comment]
> angular 16 @angular-devkit/build-angular:browser overlay-prebuilt.css not found. windows 10.

Please try upgrading to ng-zorro-antd v16.2.1.

**Comment by ramoverflow** [comment]
> > angular 16 @angular-devkit/build-angular:browser overlay-prebuilt.css not found. windows 10.
> 
> Please try upgrading to ng-zorro-antd v16.2.1.
I have already installed v16.2.1, removed node_modules & reinstall.
`  
"@angular/animations": "^16.2.0",
    "@angular/cdk": "^16.2.0",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/platform-browser": "^16.2.0",
    "@angular/platform-browser-dynamic": "^16.2.0",
    "@angular/router": "^16.2.0",
    "json-bigint": "^1.0.0",
    "ng-zorro-antd": "^16.2.1",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
`

Less resolver error:
'../../node_modules/@angular/cdk/overlay-prebuilt.css' wasn't found. 
Webpack resolver error details:
resolve '../../node_modules/@angular/cdk/overlay-prebuilt.css' in 'MY_PROJECT_FOLDER\node_modules\ng-zorro-antd\style'

**Comment by HyperLife1119** [comment]
You should use `ng-zorro-antd/ng-zorro-antd.less` instead of `ng-zorro-antd\style`

**Pull request merged**
