### PR TITLE
feat(module:calendar): support only display date of active month

### PR DESCRIPTION
**Pull request by Mr-Eve**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #4615

## What is the new behavior?
If you enable `nzMonthScope`(default `false`), then calendar only display the date of active month, not display extra date anymore.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Mr-Eve** [comment]
> 
> 
> Thanks for your pull request!
> some comments here:
> 
>     1. The issue is needed before creating any pull request, this would help others understand your proposal.
> 
>     2. test is needed

Actually, the issue is exist #4615

**Comment by Mr-Eve** [comment]
> 
> 
> Thanks for your pull request!
> some comments here:
> 
>     1. The issue is needed before creating any pull request, this would help others understand your proposal.
> 
>     2. test is needed

Issue number has been displaied in the PR describe. And I added a unit test for this feature just now.

**Comment by Mr-Eve** [comment]
Any problems?

**Comment by vthinkxie** [comment]
cc @wenqi73 
can you take a look?

**Comment by wenqi73** [comment]
@Mr-Eve 只需要加个 `[nzDisabledDate]` 即可。“仅显示当前月的日期”这种定制化的需求不是组件库应该做的。正如 issue 里面所说，用 `[nzDisabledDate]` 配合 css 就能解决该需求。欢迎再来个 PR！

**Comment by Mr-Eve** [comment]
确实. 那过两天我看看. 我重新提PR吧, 这个PR的commit都没有价值了.

**Pull request closed without merging**
