### PR TITLE
feat(cascader): add search

### LINKED ISSUE #1773: Cascader Support Filter
## What problem does this feature solve?
Cascader Component Support Filter Function

Screenshots from http://element.eleme.io/#/zh-CN/component/cascader
## What does the proposed API look like?
```
<nz-cascader
      [(ngModel)]="values"
      [nzOptions]="nzOptions"
      [nzFilterable]="true"
      (ngModelChange)="onChanges($event)">
    </nz-cascader>
```

### PR DESCRIPTION
**Pull request by wendzhue**
close #1773

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 1773

## What is the new behavior?

Now NzCascader supports filtering and sorting.

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by wendzhue** [comment]
The closing behaviour needs to be improved.

**Comment by fbchen** [comment]
@wendzhue implement the toggle effect: 
add ``` [@dropDownAnimation]="dropDownPosition"``` to the ```ul``` element

```
<ng-container *ngIf="inSearch">
      <ul ... [@dropDownAnimation]="dropDownPosition">
        ...
      </ul>
</ng-container>
```

**Comment by fbchen** [comment]
@wendzhue   in search mode, I can't navigate to the search result items by press ↑ and ↓ keys.

**Comment by wendzhue** [comment]
I would close this and create a new pr.

**Pull request closed without merging**
