### PR TITLE
feat(module:image): zoom using mouse wheel

### PR DESCRIPTION
**Pull request by ParsaArvanehPA**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [✔] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [✔] Tests for the changes have been added (for bug fixes / features)
- [] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[✔] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
The image component in <a href="https://ant.design/components/image">antd</a> supports zooming in the image with the mouse wheel, but this feature is not available in our image component.

Issue Number: N/A

## What is the new behavior?
The image can be zoomed in with the mouse wheel, and the zooming center is aligned with the mouse cursor position.

## Does this PR introduce a breaking change?
```
[ ] Yes
[✔] No
```

### CODE REVIEW

**Comment by ParsaArvanehPA** [comment]
@HyperLife1119 @Nicoss54 I would be grateful if you could review my pull request.

**Comment by Nicoss54** [comment]
> @HyperLife1119 @Nicoss54 I would be grateful if you could review my pull request.

@HyperLife1119 i am going to tackle this if you’re ok ?

**Comment by HyperLife1119** [comment]
> > @HyperLife1119 @Nicoss54 I would be grateful if you could review my pull request.
> 
> @HyperLife1119 i am going to tackle this if you’re ok ?

Give it to you :)

**Review by Nicoss54 — CHANGES_REQUESTED** [review]

**Comment by Nicoss54** [comment]
LGTM

**Pull request merged**
