### PR TITLE
fix(module:time-picker): place ViewChild decorator on correct field

### PR DESCRIPTION
**Pull request by lppedd**
This PR fixes an issue with Ivy compatibility.

- [X] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [X] <s>Tests for the changes have been added (for bug fixes / features)</s>
- [X] <s>Docs have been added / updated (for bug fixes / features)</s>

## PR Type
What kind of change does this PR introduce?
```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by Svetomechc** [comment]
Now possible to compile with Ivy?

**Comment by lppedd** [comment]
@Svetomechc no, unfortunately. There is another issue with bindings and base classes

**Comment by Svetomechc** [comment]
@lppedd what do you think the ETA on that will be? After Angular 9.0 stable release?

**Comment by lppedd** [comment]
@Svetomechc I have no idea as I'm not part of ng-zorro. I would hope for it being ready for 9 RC in a couple of weeks.

**Pull request merged**
