### PR TITLE
feat(module:date-picker): support standalone component

### PR DESCRIPTION
**Pull request by ParsaArvanehPA**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [✔] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [✔] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[✔] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the new behavior?
Updated Date picker component to work as a standalone component.

## Does this PR introduce a breaking change?
```
[ ] Yes
[✔] No
```

### CODE REVIEW

**Review by Nicoss54 — CHANGES_REQUESTED** [review]
Please make the build pass

**Comment by HyperLife1119** [comment]
Let's delete the BidiModule again :)

https://github.com/NG-ZORRO/ng-zorro-antd/issues/8229#issuecomment-1839810931

**Comment by ParsaArvanehPA** [comment]
> Let's delete the BidiModule again :)
> 
> [#8229 (comment)](https://github.com/NG-ZORRO/ng-zorro-antd/issues/8229#issuecomment-1839810931)

Sure, I will get back to you as soon as I can :)

**Comment by ParsaArvanehPA** [comment]
> Let's delete the BidiModule again :)
> 
> [#8229 (comment)](https://github.com/NG-ZORRO/ng-zorro-antd/issues/8229#issuecomment-1839810931)

Changes have been made

**Pull request merged**
