### PR TITLE
fix(module:*): patch all components with setDisabledState

### PR DESCRIPTION
**Pull request by deart1mer**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #134 #195 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Patch all components with setDisabledState. 
Work in process: 
- [x] input
- [x] input-number
- [x] select
- [x] slider
- [x] switch
- [x] rate
- [x] datepicker
- [x] timepicker
- [x] checkbox-group
- [x] radio-group
- [x] cascader

### CODE REVIEW

**Comment by deart1mer** [comment]
@vthinkxie 
Hi. I'm trying to help to patch all components with setDisabledState, but I found an unnormal behavior in some of the disabled components. I can not make a decision to fix it or not.
I found that the popup(dropdown) of components like select, datepicker, timepicker and so on won't be disabled and closed while they have been opened. 
This is not just about setDisabledState, which is related to the disabled behavior of the component itself. 
Is this an unnormal behavior? If is, should I fix it when I fix the setDisabledState, or just follow the original behavior and open another issue to fix it?

For example:
Steps:
1. Open select component's dropdown.
2. Select component disable by a timer.

Expect:
Select component close dropdown or disable the selection from user.

Current:
Select component become disabled status but dropdown selection still work for user.
image

**Comment by vthinkxie** [comment]
@deart1mer 
Thanks for your pr, the dropdown should be closed if the component is disabled.
Please open another issue and fix it if you wish.

**Comment by deart1mer** [comment]
@vthinkxie Yeah. I would like to do that.

**Comment by deart1mer** [comment]
@vthinkxie Hi, I have patched all components with `setDisabledState`. Should I fix #190 in a new pr?

**Comment by vthinkxie** [comment]
@deart1mer yes, we will merge this after review, thanks for your effort.

**Pull request merged**
