### PR TITLE
feat(module:schematics): support ng-add in standalone app

### PR DESCRIPTION
**Pull request by Laffery**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #8023

## What is the new behavior?

Support `ng-add` schematics in standalone app.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Laffery** [comment]
standlone 模式下，目前无法使用预设的 `side-menu` 模板初始化，这与 `ng generate` schematic 有关，将在后面的 pr 中支持，或对此感兴趣的朋友可以沿此继续做下去

**Comment by Nicoss54** [comment]
@simplejason seems good to me. Could you also review ?

**Review by zokizuan — APPROVED** [review]

**Comment by zokizuan** [comment]
`❯ npx nx g ng-zorro-antd:ng-add --project=workai

>  NX  Generating ng-zorro-antd:ng-add

√ Enable icon dynamic loading [ Detail: https://ng.ant.design/components/icon/en ] (y/N) · true
√ Set up custom theme file [ Detail: https://ng.ant.design/docs/customize-theme/en ] (y/N) · false
√ Choose your locale code: · en_US
√ Choose template to create project: · sidemenu
SchematicsException [Error]: Bootstrap call not found
    at findBootstrapModulePath (C:\Users\Hamza\Documents\Work\teamwave\v2frontend\nxlatest\node_modules\@schematics\angular\utility\ng-ast-utils.js:67:15)
    at getAppModulePath (C:\Users\Hamza\Documents\Work\teamwave\v2frontend\nxlatest\node_modules\@schematics\angular\utility\ng-ast-utils.js:85:32)
    at C:\Users\Hamza\Documents\Work\teamwave\v2frontend\nxlatest\node_modules\ng-zorro-antd\schematics\ng-add\setup-project\register-locale.js:27:67
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Hamza\Documents\Work\teamwave\v2frontend\nxlatest\node_modules\ng-zorro-antd\schematics\ng-add\setup-project\register-locale.js:9:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 >  NX   Bootstrap call not found

   Pass --verbose to see the stacktrace.`

**Comment by zokizuan** [comment]
please merge this pr if it fixes the above issue

**Comment by Laffery** [comment]
> standlone 模式下，目前无法使用预设的 `side-menu` 模板初始化，这与 `ng generate` schematic 有关，将在后面的 pr 中支持，或对此感兴趣的朋友可以沿此继续做下去

`side menu` is supported now!  @Nicoss54 @OriginRing @zokizuan

**Comment by Laffery** [comment]
I just run `ng add ng-zorro-antd` in standalone app and select `sidemenu` template, then it works well.

```shell
~/playground/ng16 main > ng add ng-zorro-antd                                                                                4s 17:55:27
Skipping installation: Package already installed
? Enable icon dynamic loading [ Detail: https://ng.ant.design/components/icon/en ] Yes
? Set up custom theme file [ Detail: https://ng.ant.design/docs/customize-theme/en ] Yes
? Choose your locale code: en_US
? Choose template to create project: sidemenu
CREATE src/app/icons-provider.ts (454 bytes)
CREATE src/app/pages/welcome/welcome.component.less (0 bytes)
CREATE src/app/pages/welcome/welcome.component.html (0 bytes)
CREATE src/app/pages/welcome/welcome.component.ts (292 bytes)
CREATE src/app/pages/welcome/welcome.routes.ts (187 bytes)
UPDATE package.json (1066 bytes)
UPDATE src/app/app.config.ts (783 bytes)
UPDATE src/styles.less (422 bytes)
UPDATE angular.json (3242 bytes)
UPDATE src/app/app.component.less (1245 bytes)
UPDATE src/app/app.component.html (1558 bytes)
UPDATE src/app/app.component.ts (572 bytes)
UPDATE src/app/app.routes.ts (249 bytes)
✔ Packages installed successfully.
~/playground/ng16 main !9 ?2 > npm run start                                                                                17s 17:55:49

> ng16@0.0.0 start
> ng serve

✔ Browser application bundle generation complete.

Initial Chunk Files                        | Names                        |  Raw Size
vendor.js                                  | vendor                       |   4.97 MB | 
styles.css, styles.js                      | styles                       | 891.52 kB | 
polyfills.js                               | polyfills                    | 333.16 kB | 
main.js                                    | main                         |  16.44 kB | 
runtime.js                                 | runtime                      |  12.61 kB | 

                                           | Initial Total                |   6.19 MB

Lazy Chunk Files                           | Names                        |  Raw Size
src_app_pages_welcome_welcome_routes_ts.js | pages-welcome-welcome-routes |   2.21 kB | 

Build at: 2023-11-03T09:56:09.582Z - Hash: a842d1733c00c06f - Time: 4742ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
```

**Comment by Laffery** [comment]
Should the `topnav` template be supported as well? WDYT @Nicoss54 

```json
{
  "template": {
      "type": "string",
      "default": "blank",
      "description": "Create an Angular project with using preset template.",
      "x-prompt": {
        "message": "Choose template to create project:",
        "type": "list",
        "items": [
          "blank",
          "sidemenu"
        ]
      }
    }
}
```

**Comment by Laffery** [comment]
> Hey hey @Laffery thanks a lot for your work, even if the topNav is not presented, i think it coul be a good idea to support it also as weel. Are you agree ?

Hey @Nicoss54, you are right. I have supported topnav yet.

**Comment by simplejason** [comment]
@Laffery 这个还有提交吗？如果确认已经完成我将合并

**Comment by Laffery** [comment]
> @Laffery 这个还有提交吗？如果确认已经完成我将合并

没有了

**Review by simplejason — APPROVED** [review]
LGTM

**Comment by roc41d** [comment]
Any idea if this fix is included in `ng-zorro-antd@17.0.0-beta.0`?
As i am having the same error

```
The package ng-zorro-antd@17.0.0-beta.0 will be installed and executed.
Would you like to proceed? Yes
√ Packages successfully installed.
? Enable icon dynamic loading [ Detail: https://ng.ant.design/components/icon/en ] Yes
? Set up custom theme file [ Detail: https://ng.ant.design/docs/customize-theme/en ] Yes
? Choose your locale code: en_US
? Choose template to create project: sidemenu
Bootstrap call not found
```

```
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 9.8.1
```

**Pull request merged**
