### PR TITLE
feat(module:breadcrumb): add nzRouteFn

### PR DESCRIPTION
**Pull request by HDaghash**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
No option to format or update routes for breadcrumb 

Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/6312

## What is the new behavior?

user can use `[nzRouteFn]` in order to add a custom function that receives the breadcrumb route and then can do any logic you wish such as adding params to the breadcrumb route.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by vthinkxie** [comment]
Hi, @wendellhu95 could you have a look when bandwidth available, thanks

**Review by wendellhu95 — APPROVED** [review]
LGTM. Sorry for not having had replied earlier. 

I will add doc in Chinese and we will be good to go.

**Comment by wendellhu95** [comment]
Chinese doc added.

**Comment by HDaghash** [comment]
Hello guys @wendellhu95 @vthinkxie  
By any chance are you planning to merge this PR ?

Thanks

**Review by Laffery — APPROVED** [review]
LGTM

**Pull request merged**
