### PR TITLE
fix: create image using document method to avoid ReferenceError in SSR

### PR DESCRIPTION
**Pull request by duong-le**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #6559 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by duong-le** [comment]
I don't know how to fix the failing test cases, can you help me with this?

**Review by vthinkxie — APPROVED** [review]
lgtm

**Comment by duong-le** [comment]
@vthinkxie I don't know how to fix the failing test cases, can you help me with that?

**Comment by duong-le** [comment]
@hsuanxyz Can you help me with the unit test?

**Comment by hsuanxyz** [comment]
@duong-le I have not found an alternative to the current change, until  [#1836 · jasmine/jasmine](https://github.com/jasmine/jasmine/issues/1836)  is processed.

so I suggest skipping the `previewImage` method on the server side (like https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/upload/upload-list.component.ts#L171).

**Comment by duong-le** [comment]
@hsuanxyz I skipped the `previewImage` method as below but the test case still failed. Do you think I should skip the test case? 
image

**Comment by hsuanxyz** [comment]
@duong-le try this.
```diff
private previewImage(file: File | Blob): Promise<string> {
+  if (!this.platform.isBrowser) {
+   return Promise.resolve('');
+  }
return new Promise(resolve => {
 ...
  this.ngZone.runOutsideAngular(() => {
     ...
+    const img = new Image();
-    const img = this.doc.createElement('img'); 
     ...
  });
 ...
});
}

```

**Comment by duong-le** [comment]
@hsuanxyz All test cases are now passed, please review once again. Thank you very much.

**Review by hsuanxyz — APPROVED** [review]
LGTM

**Comment by duong-le** [comment]
@hsuanxyz please release this fix as a minor version. I really need this fix in my app in production.

**Comment by hsuanxyz** [comment]
@duong-le https://github.com/NG-ZORRO/ng-zorro-antd-builds/releases/tag/11.4.0%2Bd7b9291dfd
you can use build version. 

`package.json`

```diff
  "dependencies": {
+   "ng-zorro-antd": "github:NG-ZORRO/ng-zorro-antd-builds#011764a7b2187fcf9eb05a22a44cf11e7f41b62d"
  }
```

**Pull request merged**
