### PR TITLE
fix(module:popconfirm): missing arrow

### PR DESCRIPTION
**Pull request by chenc041**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Any default nz-popconfirm will not show the 'arrow' even though it is marked as the default action.

Issue Number: [#7064](https://github.com/NG-ZORRO/ng-zorro-antd/issues/7064)

## What is the new behavior?
When using nz-popconfirm it used to have the little 'arrow' on the edge of the popconfirm dialog box;

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wendellhu95** [comment]
Hi. Thanks for this PR. Could you please make the CI pass?

**Comment by chenc041** [comment]
> Hi. Thanks for this PR. Could you please make the CI pass?

ok, wait ~

**Comment by chenc041** [comment]
> Hi. Thanks for this PR. Could you please make the CI pass?

pass~

**Review by wendellhu95 — APPROVED** [review]
LGTM

**Pull request merged**
