### PR TITLE
docs(module:table): correction of wrongly written characters

### PR DESCRIPTION
**Pull request by TeamMicLee**
docs(module:table): correction of wrongly written characters

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by wendzhue** [comment]
@TeamMicLee Welcome to contribute! Please make sure to make a pr after reading the [Contributing Guide](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md). Currently, your pr doesn't follow the guidelines.

**Comment by TeamMicLee** [comment]
@wendzhue Do I need to pull a new branch ?

**Comment by wendzhue** [comment]
@TeamMicLee No. You should commit your code with a meaningful message not just update index.zh-cn.html. And you should change the title of the pr. Please read our [Contributing Guide](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#-commit-message-guidelines).

**Comment by TeamMicLee** [comment]
@wendzhue oh, sorry. I have modified it.

**Comment by wendzhue** [comment]
@TeamMicLee **AND** the commit message as well. Like `docs(module:table): correction`.

**Comment by wilsoncook** [comment]
Need more corrections on all through docs to make a full-filled PR, a character modification is not recommended to be a complete PR.

**Comment by vthinkxie** [comment]
Due to no progress for a long time, this issue will be closed. Please contact us if you have any questions.

**Pull request closed without merging**
