### PR TITLE
feat(module:table and pagination): support custom the page size changer select values(#608)

### PR DESCRIPTION
**Pull request by hllinc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added for features
- [x] Docs have been added / updated for features

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

support custom the page size changer select values.
Issue Number: #608 

## What is the new behavior?
support custom the page size changer select values

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by hllinc** [comment]
@coveralls check failed? why?

**Comment by vthinkxie** [comment]
@hllinc it is ok, don't worry about it.

**Comment by hllinc** [comment]
@vthinkxie when will it work so that I can use in my project?

**Comment by vthinkxie** [comment]
This pr will be merged in Sat is the latest if everything is ok

**Comment by hllinc** [comment]
@vthinkxie only the 0.6.2 version support this feature? Does this version work well only in angular 5.x? my project use the angular's version is 4.2.4, oh no.

**Comment by vthinkxie** [comment]
@hllinc please upgrade to angular 5.0, there is almost no break change.

**Comment by hllinc** [comment]
@vthinkxie Can I have your qq or email?

**Pull request merged**
