### PR TITLE
fix(module:autocomplete): fix the wrong value of internal nz-auto-option

### PR DESCRIPTION
**Pull request by HyperLife1119**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fix the problem that when the dataSource is an object array, the value of the internal nz-auto-option is set incorrectly.

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by HyperLife1119** [comment]
The PR is ready. @hsuanxyz

**Review by hsuanxyz — APPROVED** [review]
LGTM

**Comment by HyperLife1119** [comment]
@simplejason It's ready.

**Comment by HyperLife1119** [comment]
When can we merge it? @OriginRing @simplejason

**Pull request merged**
