### PR TITLE
fix(module:date-picker): fix disabled date range boundary bug

### LINKED ISSUE #8805: In the 'date-picker' component. When using the date type to pass 'disabledDate', the end date cannot be selected, which is not as expected
### Reproduction link
[https://stackblitz.com/edit/angular-taetoz?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-taetoz?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
```
import { Component } from '@angular/core';

@Component({
  selector: 'nz-demo-date-picker-format',
  template: `
    <nz-date-picker [nzFormat]="dateFormat" [nzDisabledDate]="disabledDate"></nz-date-picker>
  `,
  styles: [
    `
      nz-date-picker
    `
  ]
})
export class NzDemoDatePickerFormatComponent {
  dateFormat = 'yyyy/MM/dd';
  disabledDate = (time: Date): boolean => {
    return new Date(time) < new Date("2024-09-16") || new Date(time) > new Date("2024-09-30");
  };
}

```

### What is expected?
The deadline of September 30th can be selected

### What is actually happening?
The component did not respond after clicking on the deadline of September 30th

| Environment | Info |
|---|---|
| ng-zorro-antd | 18.1.1 |
| Browser | Google Chrome Version 129.0.6668.71 (Official Build) (64-bit) |

### PR DESCRIPTION
**Pull request by WwwHhhYran**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Application (the showcase website) / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: close #8805  

## What is the new behavior?

support to pick the end date of the accessaible date range

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Laffery** [comment]
close because the original question was just a usage issue

**Comment by WwwHhhYran** [comment]
> close because the original question was just a usage issue

Although it is possible to solve the problem in the issue with a specific usage, in AntD it is possible to select the last date if we set the ‘disabledDate’, but not in ng zorro, so I think this is also a flaw in ng zorro.

> ps: AntD date based on dayjs info

**Comment by Laffery** [comment]
> Although it is possible to solve the problem in the issue with a specific usage, in AntD it is possible to select the last date if we set the ‘disabledDate’, but not in ng zorro, so I think this is also a flaw in ng zorro ?

As I can see, ng zorro supports that as well
https://stackblitz.com/edit/angular-taetoz-exnyqh?file=src%2Fapp%2Fapp.component.ts


antd:
image

ng-zorro-antd:
image

**Comment by WwwHhhYran** [comment]
> As I can see, ng zorro supports that as well https://stackblitz.com/edit/angular-taetoz-exnyqh?file=src%2Fapp%2Fapp.component.ts

In the demo of ng zorro above, if you don't use the `date-fns` library, it won't be able to automatically close the dropdown data-picker when clicking on date `2025-1-31` 🤔

**Pull request closed without merging**
