### PR TITLE
chore(release): release 10.0.0

### PR DESCRIPTION
**Pull request by hsuanxyz**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by wendellhu95** [comment]
社区互助可以把 GitHub Discussion 加上去，另外是否可以考虑把 gitter 入口去掉了？那里我们基本没有在跟社区互动

**Comment by wendellhu95** [comment]
页脚看着样式有点奇怪，最后一列宽度太小了

**Comment by vthinkxie** [comment]
> 社区互助可以把 GitHub Discussion 加上去，另外是否可以考虑把 gitter 入口去掉了？那里我们基本没有在跟社区互动

把gitter换成github discussion吧

**Comment by hsuanxyz** [comment]
GitHub Discussion 加好了，页脚是`justify-content: space-between` 应该是我们只有 3 列看上去太松散的原因 😟

**Pull request merged**
