### PR TITLE
feat(module:dropdown): improve `NzContextMenuService#create()`

### PR DESCRIPTION
**Pull request by HyperLife1119**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

`NzContextMenuService#create()` return `void`，developer cannot listen to view destroy event.

## What is the new behavior?

`NzContextMenuService#create()` will now return `EmbeddedViewRef`, developers can listen to view destroy event through `EmbeddedViewRef#onDestroy()`.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by HyperLife1119** [comment]
Reference: https://github.com/angular/angular/issues/48237

**Comment by HyperLife1119** [comment]
it's ready.

**Review by wzhudev — COMMENTED** [review]
LGTM

**Review by wzhudev — APPROVED** [review]

**Comment by wzhudev** [comment]
Thanks for contributing. A test case would be better :)

**Pull request merged**
