### PR TITLE
docs(module:table): explain the behaviour of  "loading" attribute 

### PR DESCRIPTION
**Pull request by lovelangy**
update the description to "loading" attribute

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ X] Documentation content changes
[ ] Application (the showcase website) / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```

### CODE REVIEW

**Comment by lovelangy** [comment]
@vthinkxie  thanks for your time to review the PR.  I have read the guidelines and updated the title of this PR, the commit messages as well.

**Comment by lovelangy** [comment]
@vthinkxie  can you please let me know what change should be made?

**Comment by vthinkxie** [comment]
Hi @lovelangy plz rebase your pr onto master, thanks

**Comment by vthinkxie** [comment]
closed now, you can submit another pr and rebase it onto master

**Pull request closed without merging**
